org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.48
neo_version_range=[21.1,)
loader_version_range=[4,)
mod_id=sfox
mod_name=Super Fox
mod_license=MIT
mod_version=2.0.1
mod_group_id=cz.maxtechnik
mod_authors=MaxTechnik, Suriken222, H3xyCZ
mod_description=The mod adds the ability to pick up a fox, put it on the head, which has a cute 3D-model.
